### ISSUE TITLE
can't load if i don't use 127.0.0.1

### ISSUE THREAD

**Issue by xSyrix** [putdotio/putio-sync#35] opened 2017-01-04 06:30 UTC
hi i was wondering if there is anyway i can use machine ip like 10.0.1.25 to app instead of 127.0.0.1

when i use machine ip it will not load it just stay on the spinning/loading icon but if i used 127.0.0.1 it load correctly 

please advise if there is anything setting i can tweak to allow it to load on machine ip

**Comment by cenkalti** [comment] 2017-01-06 15:31
Hello @xSyrix. We are planning to change CORS handling on put.io side. Probably it will be fixed next week. I will inform you again.

**Comment by bellwethr** [comment] 2017-01-13 05:23
+1 this is also affecting me.  I'm trying to run this on a headless server, but I'm forced to attach a monitor to configure putio-sync.

**Comment by paracycle** [comment] 2017-01-13 10:16
@bellwethr and @xSyrix, while we are working on changig the CORS infrastructure, as a temporary workaround, you can do SSH port forwarding of port 3000 from your desktop machines to port 3000 of your server and use the web page locally at http://127.0.0.1:3000

**Comment by cenkalti** [comment] 2017-01-13 10:54
@xSyrix @bellwethr from now on we are allowing requests from all origins.
I presume the problem is gone. Can you confirm?

**Comment by xSyrix** [comment] 2017-01-13 14:41
@cenkalti I did a new installation with 

go get -u github.com/putdotio/putio-sync

Than run the server and I try using local machine ip and still stuck at the spinning / loading screen 

Am I installing it right ?

**Comment by cenkalti** [comment] 2017-01-16 13:39
@xSyrix Yes, you are doing right. Can you remove the previous binary to make sure that you have installed the latest version?

**Comment by xSyrix** [comment] 2017-01-16 14:11
@cenkalti yes I reninstall it on a new OS different from the previous install. I will try again and report back the outcome

**Comment by xSyrix** [comment] 2017-01-17 00:52
@cenkalti I have reinstall on a new Ubuntu OS and it seems now it will recognise local machine ip like 10.0.1.132 and I was able to run the initial setup on the machine (putio-sync is installed) to connect to putio. 

But this does not solve the issue that it can only run on the machine itself example when I try to run http://10.0.1.132:3000 from another machine in the network than it goes back to the spinning loading page. 

Still having the issue as @bellwethr which need to have a monitor attached to check the status or setting. Please advise anything setting need to be tweak to get this working on other machine in the network.

**Comment by cenkalti** [comment] 2017-01-17 10:06
No problem. I guess we can solve this issue.

Can you see the exact error message on the browser console?

Can you see which request is failing on the "Network" tab? What are the headers and the body of the response of the failed request?

**Comment by xSyrix** [comment] 2017-01-18 05:01
@cenkalti here is some error 

SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.
File: 10.0.1.132:3000

Unhandled promise rejection Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      crossDomain: true,
      description: "Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.",
      message: "Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.",
      method: "GET",
      name: "Error",
      status: undefined,
      url: "http://127.0.0.1:3000/api/config"
   }


hope this help @cenkalti and thank younfor looking into this

**Comment by cenkalti** [comment] 2017-01-20 08:16
You are right. There are still references to 127.0.0.1 in code. Investigating...

**Comment by cenkalti** [comment] 2017-01-20 10:38
There are 3 references to 127.0.0.1 host in code:

1. This may be changed with a static string since files will always be uploaded to `"https://upload.put.io/files/"`
https://github.com/putdotio/putio-sync/blob/63160de2dece2c5ff06d5cb462d9212d0e9991b5/web/src/uploader/tus.js#L9
@tolgaakyuz Can you change it please?

1. API calls to the sync server can be made as relative URLs. Let's remove scheme and domain part:
https://github.com/putdotio/putio-sync/blob/63160de2dece2c5ff06d5cb462d9212d0e9991b5/web/src/common/request.js#L13
@tolgaakyuz Can you remove it please?

1. I am still thinking about how we can remove this part:
https://github.com/putdotio/putio-sync/blob/63160de2dece2c5ff06d5cb462d9212d0e9991b5/web/src/app/Reducer.js#L11

**Comment by xSyrix** [comment] 2017-02-07 12:31
@cenkalti, may i know is there any update on the above ?

**Comment by gonium** [comment] 2017-02-07 12:44
+1 - also affected by this. I would like to run putio-sync on my (headless) NAS.

**Comment by cenkalti** [comment] 2017-02-07 17:30
Sorry for the delay. @tolgaakyuz need to do changes that I described above (1 and 2). And we need to find a way to remove hardcoded `127.0.0.1` on 3.

@tolgaakyuz Can you give a time frame when can you start working on this issue?

**Comment by tolgaakyuz** [comment] 2017-02-07 19:24
hey. I've been kinda a super busy lately. I'll take a look these ;)

**Closed** 2020-08-08 10:42 UTC
